name: Build and Deploy Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Poetry env
        uses: SamuelJennings/cached-poetry-action@v2.0
        with:
          python-version: '3.12'

      - name: Build documentation
        run: poetry run sphinx-build -E -b html docs docs/_build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          publish_branch: gh-pages
          force_orphan: true
