name: Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'flex_menu/**'
      - 'README.md'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'docs/**'
      - 'flex_menu/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  call-docs:
    uses: django-mvp/shared/.github/workflows/docs.yml@v0.4.1
    secrets: inherit
